version: "3.9"
services:
  sale-monitor:
    build: .
    command: python -m sale_monitor.cli.main --products-csv /app/data/products.csv --state-file /app/data/state.json
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./src:/app/src:ro
      - ./requirements.txt:/app/requirements.txt:ro
    restart: unless-stopped